### ISSUE TITLE
protect pid not work

### ISSUE THREAD

**Issue by SearchGuardBy** [JKornev/hidden#10]
os : windows 10 x64 and windows 7 sp1 x64
the driver load successfuly.

![image](https://user-images.githubusercontent.com/44464478/50136421-b84db980-02d2-11e9-9c71-4d52ecde3e52.png)

when i execute "HiddlenCli  /protect pid 9948" ,it returned "Error, target 'pid' isn't allowed", and the pid  9948 is taskmgr.exe

![image](https://user-images.githubusercontent.com/44464478/50136433-c4397b80-02d2-11e9-9e04-92981615af2b.png)

so what is the problem? thank you.

**Comment by JKornev** [comment]
Hi,

Thanks for the report, I pushed a fix a780193b7c3f1b9459cc3002620b13d1e1eefb13 please check

**Comment by SearchGuardBy** [comment]
> Hi,
> 
> Thanks for the report, I pushed a fix [a780193](https://github.com/JKornev/hidden/commit/a780193b7c3f1b9459cc3002620b13d1e1eefb13) please check

i got successfly returned , but when i terminate it in the taskmgr, it can be killed. I tested it on windows 10 x64.

**Comment by JKornev** [comment]
Please explain what did you do step by step

**Comment by JKornev** [comment]
So I have dug few bugs and prepared two fixes (commits: 0e9e814c288d4640cc4bf6517605cee3795ffffd and 7ad8dcaad371cca98c381ecb8040790595e2766c). Both are related to Process Protection mechanism. 

Now driver is able to drop TERMINATE rights from handles to protected processes and threads as it expected. But task manager **is still able to terminate an application**. You should understand that a process can be terminated in different ways, for instance by ZwTerminateProcess, ZwTerminateThread system calls or by sending WM_QUIT, WM_DESTROY, WM_CLOSE messages to main process's window and so on. A Hidden.sys is able only to protect process\thread handles, it doesn't cover tricks with window messages. That's why I guess Task Manager is able to kill any process avoiding Hidden's protection on Windows 10. Possibly when you push "End task" it sends WM_DESTROY to main windows for UI applications or the same message to console window for console applications in this case application close itself.

Currently Hidden doesn't have any feature that can prevent process termination by window messages.

**Comment by sysdev-jay** [comment]
@JKornev Hi Have you checked this termination by window messages from process tab ?
Eagerly waiting for this fixed.
