### ISSUE TITLE
Multiple key and value hide no invalid

### ISSUE THREAD

**Issue by pyq881120** [JKornev/hidden#4]
sometime cause system hang
for example,  hide two key 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\abc
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\abd

hide two value(abc and abd)
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\abc\abc
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\abc\abd

**Comment by JKornev** [comment]
Thanks for the report I'll check

**Comment by JKornev** [comment]
Added the fix 5b3cf5932f3bc50fb1ef19f5a158f30cea9a18e7

But I'm not sure that it solves the issue because I haven't got a replication with parameters above. Therefore please check this fix.

If 5b3cf5932f3bc50fb1ef19f5a158f30cea9a18e7 doesn't solve an issue, please provide me more information:
1. Explain how do you replicate an issue exact, step by step
2. If possible copy of the tree HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
3. If possible memory dump when system hang (+hidden.sys and it's pdb)

Waiting for your response,
Thanks

**Comment by pyq881120** [comment]
I have not tested the new version, which is the last version of the trigger scene
attach file is rar format

`/*
The following is my test sample, hidden three consecutive keys, although the last three Key are hidden, but more of an ACPI.
I think it is CheckExcludeListRegKeyValueName function processing problems.

as for the system hang problem, I forgot How to trigger this scene
*/

NTSTATUS DriverEntry(
					 IN OUT PDRIVER_OBJECT   DriverObject,
					 IN PUNICODE_STRING      RegistryPath
					 )
{	
	ULONGLONG uId = FALSE;
	UNICODE_STRING usRegKeyPath = {0};
	

	if (InitializeRegistryFilter(DriverObject) >= 0)
	{
		RtlInitUnicodeString(&usRegKeyPath,L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\services\\abc");
		AddHiddenRegKey(&usRegKeyPath, &uId);

		RtlInitUnicodeString(&usRegKeyPath,L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\services\\abd");
		AddHiddenRegKey(&usRegKeyPath, &uId);

		RtlInitUnicodeString(&usRegKeyPath,L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\services\\abe");
		AddHiddenRegKey(&usRegKeyPath, &uId);
	}
	return STATUS_SUCCESS;
}`

![test rar](https://cloud.githubusercontent.com/assets/728727/24731880/9ba61ec0-1a9f-11e7-8d56-8ce2ceb1fecb.jpg)

**Comment by JKornev** [comment]
Ok, now I understand :) Look you can't customize driver entry by this way, because registry filter depends on other components like ConfigManager, PsMonitor etc. If you want to use only registry filter you should do something with described dependencies, at least initialize them.

Another thing if you want to hardcode any registry keys use special global variables in RegFilter.c:
```
// Use this variable for hard code path to registry keys that you would like to hide
// For instance: L"\\REGISTRY\\MACHINE\\SOFTWARE\\test_key",
// Notice: this array should be NULL terminated
CONST PWCHAR g_excludeRegKeys[] = {
	NULL
};

// Use this variable for hard code path to registry keys that you would like to hide
// For instance: L"\\REGISTRY\\MACHINE\\SOFTWARE\\test_key\\test_value",
// Notice: this array should be NULL terminated
CONST PWCHAR g_excludeRegValues[] = {
	NULL
};
```
Easy way to hide any registry\file object is to use special tool hiddencli 

Issue closed
